---
- name: Create a Service Now ticket
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a change request
      servicenow.itsm.incident:
        state: new 
        caller: "{{ sn_username }}"
        short_description: "ACM {{ policy_name }} violation"
        description:
          "{{ policy_name }} violation: one or more certificates are expiring soon in a secret in
          the namespace {{ target_namespace }} on the clusters:
          {{ target_clusters | join(', ') }}"
        impact: low
        urgency: low
      register: new_incident

    - debug:
        var: new_incident.record.number
