---
- name: Create a Service Now basic ticket
  hosts: localhost
  tasks:
    - name: Create a change request
      servicenow.itsm.incident:
        state: new 
        caller: "{{ sn_username }}"
        short_description: "Ansible basic test incident"
        description:
          "creatint a basic incident ticket fron Ansible"
        impact: low
        urgency: low
      register: new_incident

    - debug:
        var: new_incident
